name: Bump Version

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # This repo doesn't trigger Bump Version on push to `main`
  workflow_dispatch:
    inputs:
      version:
        description: New semver release version.

jobs:
  bump:
    uses: IronCoreLabs/workflows/.github/workflows/bump-version.yaml@bump-version-v1
    with:
      release_prereleases: false
      version: ${{ inputs.version }}
    secrets: inherit
