name: Typescript Publish
on:
  release:
    types:
      - "created" # triggered by Bump Version creating a release
  workflow_dispatch:
jobs:
  typescript-ci:
    # TODO: update to released workflow
    uses: IronCoreLabs/workflows/.github/workflows/typescript-release.yaml@add-typescript-release
    with:
      node_version: "24"
      pre_publish_steps: "./build.js; cd dist"
    secrets: inherit
