name: Typescript CI
on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
jobs:
  typescript-ci:
    uses: IronCoreLabs/workflows/.github/workflows/typescript-ci.yaml@typescript-ci-v0
    with:
      test_matrix_node_version: '["20", "22", "24"]'
      # this repo runs coverage in its default test command, which will fail if
      # under the thresholds defined in jest.config.js, so coverage delta doesn't matter as much
      run_coverage: false
      additional_steps: '["./build.js"]'
    secrets: inherit
