name: Typescript CI
'on':
  push:
    branches:
    - main
  pull_request: null
  workflow_dispatch: null
jobs:
  typescript-ci:
    uses: IronCoreLabs/workflows/.github/workflows/typescript-ci.yaml@typescript-ci
    with:
      # temp until https://github.com/nodejs/node/pull/46615 lands in 18. 18.16 breaks our code.
      test_matrix_node_version: '["14", "16", "18"]'
    secrets: inherit
